// team_robot.h : global settings file

#ifndef _TEAM_ROBOT_H_
#define _TEAM_ROBOT_H_

enum direction_t {
	UP, DOWN, LEFT, RIGHT, NONE
};

enum terrain_t {
	FLOOR, WALL, BOMBABLE, LASERABLE, WATER, PIT, NS_BRIDGE, EW_BRIDGE,
	DRILLABLE, UPARROW, DOWNARROW, LEFTARROW, RIGHTARROW,
	R_UPARROW, R_DOWNARROW, R_LEFTARROW, R_RIGHTARROW, 
	REDSWITCH_UP, NS_REDGATE, EW_REDGATE, BLUESWITCH_UP, HEAVYREDSWITCH_UP,
	HEAVYBLUESWITCH_UP, HEAVYGREENSWITCH_UP,  NS_BLUEGATE, EW_BLUEGATE, GREENSWITCH_UP, 
	NS_GREENGATE, EW_GREENGATE, ORANGESWITCH_UP, NS_ORANGEGATE, 
	EW_ORANGEGATE, HEAVYORANGESWITCH_UP, START, FINISH,
	REDSWITCH_DOWN, BLUESWITCH_DOWN, GREENSWITCH_DOWN, ORANGESWITCH_DOWN,
	HEAVYREDSWITCH_DOWN, HEAVYBLUESWITCH_DOWN, HEAVYGREENSWITCH_DOWN,
	HEAVYORANGESWITCH_DOWN, FLOOR_LAVA
};

enum moveable_t {
	BLOCK, GENERICBOT, MIRRORBOT, SHIELDBOT, CABOOSEBOT,
	DRILLBOT, PUSHBOT, BOMBBOT, TURNBOT, WALLCRAWLER, SWIMBOT,
	DECOYBOT, ENEMY,
	//The following aren't really moveable, but they're needed for launching
	REDIRECTBOT, BRIDGEBOT
};

enum behavior_t {
	TURNLEFT, TURNRIGHT,			// turnbot
	LEFTSIDE, RIGHTSIDE, NOBEHAVIOR				// wallcrawler
};

enum gameState_t {
	NOTFINISHED, WIN, LOSE
};

#endif 